task:
  class: HugginfaceSeq2SeqTask
  mode: evaluate
  src: source
  tgt: target
  maxlen: (464,48)
  preprocessed: True
  tokenizer:
    class: HuggingfaceTokenizer
    tokenizer_name: facebook/bart-base
  dataloader:
    train-distill:
      class: InMemoryDataLoader
      sampler:
        class: SequentialSampler
        max_samples: 128
  data:
    train-distill:
      class: JsonDataset
      path: data/train.index.json
  model:
    class: HuggingfaceBartModel
    pretrained_model: facebook/bart-base
  generator:
    class: SelfContainedGenerator
    num_beams: 5
    max_length: 80
    min_length: 0
    no_repeat_ngram_size: 4
    length_penalty: 0.8
    early_stopping: True
  evaluator:
    class: Evaluator
    save_hypo_dir: train/distill
env:
  device: cuda
  no_warning: True


