task:
  class: Seq2SeqTask
  mode: evaluate
  src: src
  tgt: tgt
  maxlen: (1024,400)
  preprocessed: True
  tokenizer:
    class: HuggingfaceTokenizer
    tokenizer_name: facebook/bart-base
  dataloader:
    test:
      class: InMemoryDataLoader
      sampler:
        class: SequentialSampler
        max_samples: 64
  data:
    test:
      class: JsonDataset
      sort_samples: True
      path: data/test.index.json
  model:
    class: Seq2Seq
    encoder:
      class: TransformerEncoder
      num_layers: 6
      d_model: 512
      n_head: 8
      dim_feedforward: 2048
      dropout: 0.1
      activation: 'relu'
    decoder:
      class: TransformerDecoder
      num_layers: 6
      d_model: 512
      n_head: 8
      dim_feedforward: 2048
      dropout: 0.1
      activation: 'relu'
    share_embedding: decoder-input-output
    d_model: 512
    path: checkpoints/best.pt
  generator:
    class: SequenceGenerator
    search:
      class: BeamSearch
      maxlen_coef: (0, 400)
      beam: 4
      lenpen: 2.0
  evaluator:
    class: Evaluator
    metric:
      rouge:
        class: Rouge
        ngram: 1,2,l
env:
  device: cuda
  fp16: True
  no_warning: True
  no_progress_bar: True
