task:
  class: Seq2SeqTask
  mode: preprocess
  src: src
  tgt: tgt
  maxlen: (1024,400)
  tokenizer:
    class: HuggingfaceTokenizer
    tokenizer_name: facebook/bart-base
dataset:
  class: ParallelTextDataset
data:
  train:
    path:
      src: data/train.tgt
      tgt: data/train.tgt
    output_path: data/train.ae.index.json
  valid:
    path:
      src: data/val.tgt
      tgt: data/val.tgt
    output_path: data/val.ae.index.json
  test:
    path:
      src: data/test.tgt
      tgt: data/test.tgt
    output_path: data/test.ae.index.json

