task:
  class: HugginfaceSeq2SeqTask
  mode: train
  src: src
  tgt: tgt
  maxlen: (1024,300)
  preprocessed: True
  tokenizer:
    class: HuggingfaceTokenizer
    tokenizer_name: facebook/bart-base
  dataloader:
    train:
      class: InMemoryDataLoader
      sampler:
        class: ShuffleSampler
        max_samples: 32
    valid:
      class: InMemoryDataLoader
      sampler:
        class: SequentialSampler
        max_samples: 128
    test:
      class: InMemoryDataLoader
      sampler:
        class: SequentialSampler
        max_samples: 128
  data:
    train:
      class: JsonDataset
      path: data/train.index.json
    valid:
      class: JsonDataset
      sort_samples: True
      path: data/val.index.json
    test:
      class: JsonDataset
      sort_samples: True
      path: data/test.index.json
  model:
    class: HuggingfaceBartModel
    pretrained_model: facebook/bart-base
  criterion:
      class: LabelSmoothedCrossEntropy
      epsilon: 0.1
  trainer:
    class: Trainer
    optimizer:
      class: Adafactor
      lr:
        class: PolynomialDecayScheduler
        max_rate: 3e-5
        warmup_steps: 500
        total_steps: 15000
      clip_norm: 0.
      relative_step: False
      scale_parameter: False
      warmup_init: False
      update_frequency: 2
    max_steps: 15000
    save_steps: 1000
    assess_by: valid.criterion
    save_model_dir: checkpoints
env:
  device: cuda
  fp16: True
  no_warning: True
  no_progress_bar: True

