task:
  class: HugginfaceSeq2SeqTask
  mode: train
  src: src
  tgt: tgt
  maxlen: (1024,400)
  preprocessed: True
  tokenizer:
    class: HuggingfaceTokenizer
    tokenizer_name: facebook/bart-base
  dataloader:
    train:
      class: InMemoryDataLoader
      sampler:
        class: ShuffleSampler
        max_samples: 32
    valid:
      class: InMemoryDataLoader
      sampler:
        class: SequentialSampler
        max_samples: 128
    test:
      class: InMemoryDataLoader
      sampler:
        class: SequentialSampler
        max_samples: 128
  data:
    train:
      class: JsonDataset
      path: data/train.index.json
    valid:
      class: JsonDataset
      sort_samples: True
      path: data/val.index.json
    test:
      class: JsonDataset
      sort_samples: True
      path: data/test.index.json
  model:
    class: HuggingfaceBartModel
    pretrained_model: facebook/bart-base
  criterion:
    class: LabelSmoothedCrossEntropy
    epsilon: 0.1
  trainer:
    class: Trainer
    optimizer:
      class: HuggingfaceAdamW
      lr: 5e-5
      clip_norm: 0.
      eps: 1e-8
    max_steps: 10000
    validate_interval_step: 2000
    assess_by: valid.rouge-1
    save_model_dir: checkpoints
  generator:
    class: SelfContainedGenerator
    num_beams: 4
    max_length: 400
  evaluator:
    class: Evaluator
    metric:
      rouge:
        class: Rouge
        ngram: 1,2,l
env:
  device: cuda
  fp16: True
  no_warning: True
  no_progress_bar: True

