task:
  class: Seq2SeqTask
  mode: train
  src: src
  tgt: tgt
  maxlen: (1024,400)
  preprocessed: True
  tokenizer:
    class: HuggingfaceTokenizer
    tokenizer_name: facebook/bart-base
  dataloader:
    train:
      class: InMemoryDataLoader
      sampler:
        class: ShuffleSampler
        max_samples: 64
    valid:
      class: InMemoryDataLoader
      sampler:
        class: SequentialSampler
        max_samples: 128
    test:
      class: InMemoryDataLoader
      sampler:
        class: SequentialSampler
        max_samples: 128
  data:
    train:
      class: JsonDataset
      path: data/train.index.json
    valid:
      class: JsonDataset
      sort_samples: True
      path: data/val.index.json
    test:
      class: JsonDataset
      sort_samples: True
      path: data/test.index.json
  model:
    class: HuggingfaceBartModel
    pretrained_model: facebook/bart-base
  criterion:
    class: LabelSmoothedCrossEntropy
    epsilon: 0.1
  trainer:
    class: Trainer
    optimizer:
      class: AdamW
      lr:
        class: PolynomialDecayScheduler
        max_rate: 5e-5
        warmup_steps: 500
        total_steps: 15000
      clip_norm: 0.
      betas: (0.9, 0.98)
      eps: 1e-8
      weight_decay: 1e-2
    max_epochs: 100
    max_steps: 1000000
    validate_interval_step: 4000
    assess_by: valid.criterion
    assess_reverse: True
    save_model_dir: checkpoints
  generator:
    class: SelfContainedGenerator
    num_beams: 4
    max_length: 400
  evaluator:
    class: Evaluator
    metric:
      rouge-1:
        class: Rouge
        ngram: 1
      rouge-2:
        class: Rouge
        ngram: 2
      rouge-l:
        class: Rouge
        ngram: l
env:
  device: cuda
  fp16: True
  no_warning: True
  no_progress_bar: True

