task:
  class: ViTTask
  mode: train
  dataloader:
    train:
      class: InMemoryDataLoader
      sampler:
        class: ShuffleSampler
        max_samples: 128
    test:
      class: InMemoryDataLoader
      sampler:
        class: SequentialSampler
        max_samples: 128
  data:
    train:
      class: ImageDataset
      path: 3rdparty/ViT/data/cifar/train
    test:
      class: ImageDataset
      path: 3rdparty/ViT/data/cifar/test
  model:
    class: ViTModel
    encoder:
      class: ImageTransformerEncoder
      num_layers: 6
      d_model: 128
      n_head: 8
      dim_feedforward: 512
      dropout: 0.1
      activation: 'relu'
    height: 32
    width: 32
    patch_size: 4
    d_model: 128
    labels: 100
  criterion:
    class: CrossEntropy
  trainer:
    class: Trainer
    optimizer:
      class: AdamW
      lr:
        class: InverseSquareRootRateScheduler
        warmup_steps: 4000
        rate: 5e-4
      clip_norm: 0.
      weight_decay: 1e-2
      betas: (0.9, 0.98)
    max_steps: 50000
    validate_interval_step: 4000
    assess_by: test.acc
    save_model_dir: checkpoints
  generator:
    class: Generator
  evaluator:
    class: Evaluator
    metric:
      acc:
        class: Accuracy
env:
  device: cuda
  fp16: True
