task:
  class: ViTTask
  mode: train
  dataloader:
    train:
      class: InMemoryDataLoader
      sampler:
        class: ShuffleSampler
        max_samples: 128
    test:
      class: InMemoryDataLoader
      sampler:
        class: SequentialSampler
        max_samples: 128
  data:
    train:
      class: ImageDataset
      path: 3rdparty/ViT/data/cifar/train
    test:
      class: ImageDataset
      path: 3rdparty/ViT/data/cifar/test
  model:
    class: ViTModel
    encoder:
      class: ImageTransformerEncoder
      num_layers: 6
      d_model: 128
      n_head: 8
      dim_feedforward: 512
      dropout: 0.1
      activation: 'gelu'
      normalize_before: True
    height: 32
    width: 32
    patch_size: 4
    d_model: 128
    labels: 100
  criterion:
    class: CrossEntropy
  trainer:
    class: Trainer
    optimizer:
      class: AdamW
      lr:
        class: CosineAnnealingRateScheduler
        warmup_steps: 1000
        max_rate: 1e-3
        total_steps: 100000
      clip_norm: 0.
      weight_decay: 1e-2
      betas: (0.9, 0.999)
    max_steps: 100000
    validate_interval_epoch: 1
    assess_by: test.acc
    save_model_dir: checkpoints
  generator:
    class: Generator
  evaluator:
    class: Evaluator
    metric:
      acc:
        class: Accuracy
env:
  device: cuda
  fp16: True
